### ISSUE TITLE
Windows / Multi-processes 

### ISSUE THREAD

**Issue by fjribi** [BlockScience/ZarghamPapers#1]
Hello,

I got some troubles when running the code on windows (Jupyter NB / Anaconda) using context=exec_mode.multi_proc. We got this type of errors ("NameError: name 'np' is not defined") when we call run.execute(). The variables are not propagated correctly to forked processes when running the code on windows. The worked around was to use the following code

```
import os
if os.name == 'nt': #to check if we are running on windows
    import dill
    dill.settings['recurse'] = True #to force propagating variables to forked processes in windows
```

Given that this issue is common to all cadCAD notebooks, I added the code above to ...\Lib\site-packages\cadCAD\__init__.py

That fixes the errors and the notebooks work fine now.
Could you please check if it's the best way to handle the issue and whether it's worth taking it into account in future upgrades of cadCAD?

Thanks,

**Comment by mzargham** [comment]
Apologies @fjribi we are still sometimes finding issues in windows environments.

@matttyb80 works with cadCAD on a daily basis and uses windows; 

@matttyb80 do you have a solution or a work around?

**Comment by fjribi** [comment]
Thank you for your feedback. I'm particularly interested in your "Economic Games as Estimators" paper and this repository for a potential use-case that's why I posted at first the issue here. But I will keep following the issue at cadCAD level on [#104.](https://github.com/BlockScience/cadCAD/issues/104).

**Comment by mzargham** [comment]
Sounds good. I am glad to hear you are interested in this paper. The repo with the simulations for the paper was cleaned up a bit by @aclarkData so it would be more accessible. There is additional related work:

this repo is mostly scratchwork of mine but many other teams are building cool stuff based on it:
https://github.com/BlockScience/conviction

Also for a more operationalized view of bonding curves, check out the models here:
https://gitlab.com/grassrootseconomics/cic-modeling/-/tree/master/Simulation
this work is ongoing with Grassroots economics and the red cross

**Comment by fjribi** [comment]
Thank you for your feedback and reactivity, I will take a closer look at your recommended links.
Regards,
